server:
  port: 8084

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/

spring:
  application:
    name: service-hello

info:
  app.author: TjSanshao
  app.name: @project.artifactId@
  app.version: @project.version@